name: Build Python wheels and make release

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-and-test-wheels.yml'
      - 'include/**'
      - 'scripts/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - 'setup.py'
      - 'pyproject.toml'
    branches: [master]
  pull_request:
    paths:
      - '.github/workflows/build-and-test-wheels.yml'
    branches: [master]
  release:
    types: [published]

env:
  DYLD_LIBRARY_PATH: "/opt/homebrew/opt/openal-soft/lib:/usr/local/opt/openal-soft/lib"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Report OS
        run: |
          echo ${{ matrix.os }}
          echo ${{ runner.os }}
          uname -p

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build manylinux wheels
        if: matrix.os == 'ubuntu-24.04'
        uses: pypa/cibuildwheel@v3.3.1
        env:
          # Configure cibuildwheel to build native archs, and some emulated ones
          CIBW_ARCHS_LINUX: x86_64
          CIBW_BUILD_VERBOSITY: 1

      - name: Build macOS Apple Silicon wheels
        if: matrix.os == 'macos-14'
        uses: pypa/cibuildwheel@v3.3.1
        env:
          CIBW_ARCHS_MACOS: arm64
          CIBW_ENVIRONMENT_MACOS: VIZDOOM_MACOS_ARCH=arm64 HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 MACOSX_DEPLOYMENT_TARGET=14.0
          CIBW_BUILD_VERBOSITY: 1

      - name: Report built wheels
        run: |
          ls -l ./wheelhouse/*.whl

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: ./wheelhouse/*.whl

      - name: Attach wheels to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: ./wheelhouse/*.whl
